### ISSUE TITLE
Lacking of Industry Best Practics, documentation and Login Procedure

### ISSUE THREAD

**Issue by enomado** [Owez/axum-auth#16]
Guys! I'm very appreciative your work, but... 

You need to understand. This library will be used probably as the most entry level simple login for beginners. But its actually the hardest. 

1. please, add some notes on `http basic auth` standart.

2. `TypedHeader<Authorization<..>>` is not clear for me at all. its undocumented, its something I dont want to use when I just want to secure some handlers, and there is no place in axum documentation where it says "oh, use me for auth"

3. You not must, but you probably should introduce to newbies strategies of login "at all". As I understand you offer user to use BasicAuth as extractor to any protected handler? Where I, as newbie developer can know is it good practice? Or should I better secure my handler by middleware? 
Why dont you write about this option, just like, oh, its simple as

```
  let (mut parts, _) = req.into_parts();
  let auth = AuthBasic::from_request_parts(&mut parts, &()).await.unwrap();
```
4.  There is actually no any `login story` in examples. I dont see redirect from protected page, I dont see login page, which should write the token, nor place where this token must be written from frontend side.

Sorry, I know this crate is in maintaince mode, but there are many reasons for me to not use axum-login because of its macroses everywhere. I wanted simplicity, but must see any examples and solutions to actually use simple basic auth in a whole infrastructure

**Comment by Owez** [comment]
Evening, this crate is intended for use with basic auth if you do know how basic auth/bearer auth works in general. I agree that `TypedHeader<Authorization<..>>` is confusing and that's why this crate was originally created, the reference to `TypedHeader<Authorization<..>>` was a note that you can use the axum standards if you want.

I think the README content is fine and I'm not sure what you mean by the "just like, oh, its simple as" middle code block. Figure out what you want to use in your stack and find an appropriate library for the job is my advice 🤷

**Comment by enomado** [comment]
>Evening, this crate is intended for use with basic auth if you do know how basic auth/bearer auth works in general.

Absolutely no. Web is very old. There are tons scenarios - you can change cookie on backend, you can ask browser for dialog sending WWW-authorization header. You can even run api from proxy and use its own auth. My claim is - **you dont provide any example working scenario**. I mean, reading readme and code I dont understand how was supposed to ask user credentials, how to reject, etc.

>I'm not sure what you mean by

I mean that there is two mechanisms - extractors and middleware. You dont provide any information about what is best practice to decorate handler to be protected. I'm talking about this example - https://docs.rs/axum/latest/axum/middleware/fn.from_extractor.html it is literally what you should write in readme. 

>Figure out what you want to use in your stack and find an appropriate library for the job is my advice 🤷

I repeat again - my message is: it is more timesaving to read other libraries code, blogposts, axum documentation, and write auth from scratch by myself, than try to figure out how to properly use this library.

**Comment by Owez** [comment]
I made it for use as a handler at the extractor-level as shown in the examples and that's what I've used it for. As the top note says, you may very well use https://docs.rs/axum/latest/axum/middleware/fn.from_extractor.html. If I was writing middleware, I'd use that too – that's why the note is there.
